[tool.poetry]
name = "docker-inspector"
version = "0.1.0"
description = ""
authors = ["antonio <mr.antonsilin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
textual = "^0.56.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

